import { Injectable } from '@nestjs/common';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import * as z from 'zod/v4';

import { BOOK_STATUSES, type Book } from '@books/contracts';

import { JwtUser } from '../auth/auth.models';
import { BooksService } from '../books/books.service';
import { ApiDocumentationService } from '../docs/api-documentation.service';

const BOOKS_DOCS_URI = 'books://api-docs';
const BOOKS_OPENAPI_URI = 'books://openapi.json';

const BookSchema = z.object({
  id: z.string(),
  title: z.string(),
  author: z.string(),
  description: z.string().optional(),
  publishedYear: z.number().int().optional(),
  status: z.enum(BOOK_STATUSES),
  createdAt: z.string(),
  updatedAt: z.string(),
});

const bookFields = {
  title: z.string().min(1).max(160),
  author: z.string().min(1).max(120),
  description: z.string().max(1000).optional(),
  publishedYear: z.number().int().min(1000).max(2100).optional(),
  status: z.enum(BOOK_STATUSES).optional(),
};

const readOnlyAnnotations = {
  readOnlyHint: true,
  destructiveHint: false,
  idempotentHint: true,
  openWorldHint: false,
};

const writeAnnotations = {
  readOnlyHint: false,
  destructiveHint: false,
  idempotentHint: false,
  openWorldHint: false,
};

const BOOKS_DOCUMENTATION = `# Books API and MCP capabilities

This server exposes the same owner-scoped BooksService through REST and MCP.

## REST

- \`GET /api/books\` lists books and supports \`q\` and \`status\`.
- \`GET /api/books/{id}\` gets one book.
- \`POST /api/books\` creates a book.
- \`PATCH /api/books/{id}\` updates a book.
- \`DELETE /api/books/{id}\` deletes a book.

## MCP tools

- \`list_books\`
- \`get_book\`
- \`create_book\`
- \`update_book\`
- \`delete_book\`

Every operation is scoped to the authenticated JWT user. The model cannot choose an owner ID.
Book statuses are \`to_read\`, \`reading\`, and \`read\`.
`;

@Injectable()
export class McpServerFactory {
  constructor(
    private readonly books: BooksService,
    private readonly documentation: ApiDocumentationService,
  ) {}

  create(user: JwtUser): McpServer {
    const server = new McpServer(
      { name: 'books-mcp-poc', version: '1.0.0' },
      {
        instructions:
          'Use books://api-docs to understand the Books API. All book tools are scoped to the authenticated user.',
      },
    );

    server.registerResource(
      'books-api-docs',
      BOOKS_DOCS_URI,
      {
        title: 'Books API guide',
        description: 'A concise guide to the REST API and matching MCP tools.',
        mimeType: 'text/markdown',
      },
      () => ({
        contents: [
          {
            uri: BOOKS_DOCS_URI,
            mimeType: 'text/markdown',
            text: BOOKS_DOCUMENTATION,
          },
        ],
      }),
    );

    server.registerResource(
      'books-openapi',
      BOOKS_OPENAPI_URI,
      {
        title: 'Generated Books OpenAPI document',
        description: 'The live Swagger/OpenAPI document generated by NestJS.',
        mimeType: 'application/json',
      },
      () => ({
        contents: [
          {
            uri: BOOKS_OPENAPI_URI,
            mimeType: 'application/json',
            text: JSON.stringify(this.documentation.getDocument(), null, 2),
          },
        ],
      }),
    );

    server.registerTool(
      'list_books',
      {
        title: 'List books',
        description:
          'List up to 100 books belonging to the authenticated user. Optionally search title or author and filter by reading status.',
        inputSchema: {
          q: z.string().max(120).optional(),
          status: z.enum(BOOK_STATUSES).optional(),
          limit: z.number().int().min(1).max(100).default(50),
        },
        outputSchema: {
          books: z.array(BookSchema),
          total: z.number().int().min(0),
        },
        annotations: readOnlyAnnotations,
      },
      async ({ q, status, limit }) =>
        this.runTool(async () => {
          const result = await this.books.list(user.sub, { q, status, limit });
          return { books: result.books, total: result.total };
        }),
    );

    server.registerTool(
      'get_book',
      {
        title: 'Get a book',
        description: 'Get one book by ID when it belongs to the authenticated user.',
        inputSchema: { id: z.string().min(1) },
        outputSchema: { book: BookSchema },
        annotations: readOnlyAnnotations,
      },
      async ({ id }) =>
        this.runTool(async () => ({ book: await this.books.get(user.sub, id) })),
    );

    server.registerTool(
      'create_book',
      {
        title: 'Create a book',
        description:
          'Create a book for the authenticated user. Use only after the user explicitly allows changes.',
        inputSchema: bookFields,
        outputSchema: { book: BookSchema },
        annotations: writeAnnotations,
      },
      async (input) =>
        this.runTool(async () => ({
          book: await this.books.create(user.sub, input),
        })),
    );

    server.registerTool(
      'update_book',
      {
        title: 'Update a book',
        description:
          'Update fields on one owned book. Use only after the user explicitly allows changes.',
        inputSchema: {
          id: z.string().min(1),
          title: bookFields.title.optional(),
          author: bookFields.author.optional(),
          description: bookFields.description,
          publishedYear: bookFields.publishedYear,
          status: bookFields.status,
        },
        outputSchema: { book: BookSchema },
        annotations: writeAnnotations,
      },
      async ({ id, ...input }) =>
        this.runTool(async () => ({
          book: await this.books.update(user.sub, id, input),
        })),
    );

    server.registerTool(
      'delete_book',
      {
        title: 'Delete a book',
        description:
          'Permanently delete one owned book. Use only after the user explicitly allows changes.',
        inputSchema: { id: z.string().min(1) },
        outputSchema: { book: BookSchema },
        annotations: {
          ...writeAnnotations,
          destructiveHint: true,
          idempotentHint: true,
        },
      },
      async ({ id }) =>
        this.runTool(async () => ({
          book: await this.books.remove(user.sub, id),
        })),
    );

    return server;
  }

  private async runTool<T extends Record<string, unknown>>(
    operation: () => Promise<T>,
  ): Promise<{
    content: [{ type: 'text'; text: string }];
    structuredContent?: T;
    isError?: boolean;
  }> {
    try {
      const result = await operation();
      return {
        content: [{ type: 'text', text: JSON.stringify(result, null, 2) }],
        structuredContent: result,
      };
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'The book operation failed';
      return {
        content: [{ type: 'text', text: message }],
        isError: true,
      };
    }
  }
}

export type { Book };
